language: python
python:
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - redis-cli ping
  - psql -c "CREATE DATABASE flaskrest02;" -U postgres
  - psql -c "CREATE USER flaskrest02 WITH PASSWORD 'flaskrest02';" -U postgres

script:
  - nosetests

after_success:
 - codecov

services:
  - redis-server
  - postgresql
